version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server
    container_name: jwttoken_db
    restart: always
    environment:
      SA_PASSWORD: kutluaypass
      ACCEPT_EULA: Y
      MSSQL_DATABASE: jwtTokenDB
      MSSQL_USER: kutluaylav
      MSSQL_PASSWORD: lav
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/opt/mssql

volumes:
  db_data: